### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by vrunoa** [Urucas/zoster#10]
Hi
   
Can I use zoster to test my app for Deep links. I have tried installing it on  my mac but i am getting this error
```bash
> fsevents@1.0.15 install /Users/UG00334381/Desktop/zoster-master/node_modules/fsevents

> node-pre-gyp install --fallback-to-build

 

[fsevents] Success: "/Users/UG00334381/Desktop/zoster-master/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote

 

> zoster@0.2.4 install /Users/UG00334381/Desktop/zoster-master

> make clean && make node

 

TypeError: Path must be a string. Received undefined

    at assertPath (path.js:7:11)

    at Object.basename (path.js:1355:5)

    at buildResult (/Users/UG00334381/Desktop/zoster-master/node_modules/babel/lib/babel/file.js:22:18)

    at output (/Users/UG00334381/Desktop/zoster-master/node_modules/babel/lib/babel/file.js:70:18)

    at walk (/Users/UG00334381/Desktop/zoster-master/node_modules/babel/lib/babel/file.js:128:5)

    at files (/Users/UG00334381/Desktop/zoster-master/node_modules/babel/lib/babel/file.js:132:5)

    at module.exports (/Users/UG00334381/Desktop/zoster-master/node_modules/babel/lib/babel/file.js:152:5)

    at Object.<anonymous> (/Users/UG00334381/Desktop/zoster-master/node_modules/babel/lib/babel/index.js:147:1)

    at Module._compile (module.js:573:32)

    at Object.Module._extensions..js (module.js:582:10)

TypeError: Path must be a string. Received undefined

    at assertPath (path.js:7:11)

    at Object.basename (path.js:1355:5)

    at buildResult (/Users/UG00334381/Desktop/zoster-master/node_modules/babel/lib/babel/file.js:22:18)

    at output (/Users/UG00334381/Desktop/zoster-master/node_modules/babel/lib/babel/file.js:70:18)

    at walk (/Users/UG00334381/Desktop/zoster-master/node_modules/babel/lib/babel/file.js:128:5)

    at files (/Users/UG00334381/Desktop/zoster-master/node_modules/babel/lib/babel/file.js:132:5)

    at module.exports (/Users/UG00334381/Desktop/zoster-master/node_modules/babel/lib/babel/file.js:152:5)

    at Object.<anonymous> (/Users/UG00334381/Desktop/zoster-master/node_modules/babel/lib/babel/index.js:147:1)

    at Module._compile (module.js:573:32)

    at Object.Module._extensions..js (module.js:582:10)

make: *** [node] Error 1

 

npm ERR! Darwin 15.6.0

npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"

npm ERR! node v7.1.0

npm ERR! npm  v4.0.2

npm ERR! code ELIFECYCLE

npm ERR! zoster@0.2.4 install: `make clean && make node`

npm ERR! Exit status 2

npm ERR! 

npm ERR! Failed at the zoster@0.2.4 install script 'make clean && make node'.

npm ERR! Make sure you have the latest version of node.js and npm installed.

npm ERR! If you do, this is most likely a problem with the zoster package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR!     make clean && make node

npm ERR! You can get information on how to open an issue for this project with:

npm ERR!     npm bugs zoster

npm ERR! Or if that isn't available, you can get their info via:

npm ERR!     npm owner ls zoster

npm ERR! There is likely additional logging output above.

 

npm ERR! Please include the following file with any support request:

npm ERR!     /Users/UG00334381/Desktop/zoster-master/npm-debug.log​
```

**Comment by vrunoa** [comment]
I have to refactor the code to avoid using make. Can you try building the module manually:
```bash
git clone https://github.com/Urucas/zoster.git && cd zoster
npm install
npm install -g .
```

**Comment by sindhu576** [comment]
I cloned it and give npm install

Here it self ,bcoz of make node n clean...its failed....

**Comment by sindhu576** [comment]
its still not working for me..can you help me with this

**Comment by vrunoa** [comment]
@sindhu576 i'm refactor the code to work, i'll ping you by the start of next week, it will probably done

**Comment by sindhu576** [comment]
Hii..is that done..
