### ISSUE TITLE
Error while running zoster test with simple.json capabilities.

### ISSUE THREAD

**Issue by pavankumar9** [Urucas/zoster#9]
Please help me in resolving the issue:

> zoster@0.2.4 start /Users/pavan/mydata/office/mobile_auto/zoster
> ./bin/zoster "--test" "/Users/pavan/mydata/office/mobile_auto/zoster/examples/simple.json"

/Users/pavan/mydata/office/mobile_auto/zoster/node/index.js:64
  instance.adb = new _adbjs2['default']();
                 ^
TypeError: object is not a function
    at zoster (/Users/pavan/mydata/office/mobile_auto/zoster/node/index.js:64:18)
    at module.exports (/Users/pavan/mydata/office/mobile_auto/zoster/server.js:6:3)
    at module.exports (/Users/pavan/mydata/office/mobile_auto/zoster/exec.js:20:5)
    at Object.<anonymous> (/Users/pavan/mydata/office/mobile_auto/zoster/bin/zoster:32:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)

**Comment by pavankumar9** [comment]
Any update?

**Comment by vrunoa** [comment]
@pavankumar9 sorry for the late reply. I'll take a look at this as soon as I can. I'll give a feedback by the weekend
